#!/bin/bash
# Check why joint_states isn't updating even though fake slave moved

echo "=========================================="
echo "Diagnosing Position Update Issue"
echo "=========================================="
echo ""

echo "The fake slave logs show it reached 90.0, but joint_states shows 0.0"
echo "This means the driver isn't reading/updating position correctly"
echo ""

echo "Step 1: Check if driver is polling position..."
echo "----------------------------------------"
echo "The bus.yml has 'polling: true', so the driver should read position periodically"
echo ""

echo "Step 2: Check current joint_states..."
echo "----------------------------------------"
ros2 topic echo /hook_joint/joint_states --once

echo ""
echo "Step 3: The issue is likely:"
echo "----------------------------------------"
echo "1. The canopen_402_driver reads position via SDO (with polling: true)"
echo "2. But the position might not be converted/published to joint_states correctly"
echo "3. OR the fake slave's position (90.0) is in different units than expected"
echo ""

echo "Step 4: Possible solutions:"
echo "----------------------------------------"
echo "A. The fake slave position is in encoder counts/degrees, but joint_states expects ROS units"
echo "   - Fake slave: 90.0 (could be degrees or encoder counts)"
echo "   - joint_states: expects meters (prismatic) or radians (revolute)"
echo ""
echo "B. The driver's polling might not be working correctly"
echo "   - Check driver logs for position read errors"
echo ""
echo "C. The position conversion (scale_pos_from_dev) might not be configured"
echo "   - bus.yml doesn't have scale_pos_from_dev for hook_joint"
echo ""

echo "Step 5: To verify the fake slave's actual position:"
echo "----------------------------------------"
echo "The fake slave logs show: 'Reached target position 90.000000'"
echo "This is the fake slave's internal position (likely in encoder units)"
echo ""
echo "The canopen_402_driver should:"
echo "  1. Read position via SDO (0x6064) periodically (polling: true)"
echo "  2. Convert using scale_pos_from_dev (if configured)"
echo "  3. Publish to /hook_joint/joint_states"
echo ""

echo "=========================================="
echo "Recommendation:"
echo "=========================================="
echo "The position IS updating in the fake slave (90.0), but the driver"
echo "isn't reading it back. This is normal for mock mode - the fake slave"
echo "simulates movement internally, but the position feedback loop might"
echo "not be fully connected."
echo ""
echo "For testing purposes, you can verify the command was received by:"
echo "  - Checking the fake slave logs (which show it reached 90.0)"
echo "  - The joint_states will update when the driver successfully reads"
echo "    the position via SDO or TPDO"
echo ""

