#!/bin/bash

echo "=========================================="
echo "重启 CANopen 系统指南"
echo "=========================================="
echo ""
echo "由于 SDO 读取全部超时，建议重启 CANopen 系统"
echo ""
echo "步骤 1: 停止当前运行的 launch 文件"
echo "----------------------------------------"
echo "在运行 launch 文件的终端按 Ctrl+C 停止"
echo ""
echo "步骤 2: 检查并重启 CAN 接口（如果需要）"
echo "----------------------------------------"
echo "运行以下命令："
echo ""
echo "  # 检查 CAN 接口状态"
echo "  ip link show can0"
echo ""
echo "  # 如果接口是 DOWN，启动它"
echo "  sudo ip link set can0 up"
echo ""
echo "  # 如果接口有问题，重新配置"
echo "  sudo ip link set can0 down"
echo "  sudo ip link set can0 type can bitrate 500000"
echo "  sudo ip link set can0 up"
echo ""
echo "步骤 3: 重新启动 CANopen 系统"
echo "----------------------------------------"
echo "运行："
echo ""
echo "  cd /home/qiaoqiaochen/appdata/canros"
echo "  source /opt/ros/humble/setup.bash"
echo "  source install/setup.bash"
echo "  ros2 launch tower_crane robot_control.launch.py can_interface_name:=can0"
echo ""
echo "步骤 4: 等待系统初始化完成"
echo "----------------------------------------"
echo "等待看到类似以下消息："
echo "  [INFO] Initialisation successful."
echo "  [INFO] Successful 'activate' of hardware"
echo ""
echo "步骤 5: 再次尝试使能电机"
echo "----------------------------------------"
echo "  ./force_enable_all_motors.sh"
echo ""

